In [5]:
data = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world."""

clean_data = data.strip()
clean_data

"Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world."

In [6]:
max_char = 300
overlap = 100
chunks = []
i = 1

while i < len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i = i+max_char - overlap

chunks   

["aking an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today",
 ".5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 202",
 'ackgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron ',
 'gnificant milestone, Sudhanshu remained focused on his mission. Even after th

In [7]:
len(chunks)

4

In [28]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-88d2a9f6c56b8b5093241fe0d73eaab7740bd68154d4751a2963928ebac6757f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [18]:
import os
from dotenv import load_dotenv
from euriai import EuriaiEmbedding, EuriaiEmbeddingClient

load_dotenv()
API_KEY = os.getenv("EURIAI_API_AKY")
client = EuriaiEmbeddingClient(model="text-embedding-3-small", api_key=API_KEY)
client

In [29]:
for i in chunks:
    embeddings = generate_embeddings(i)
    print(embeddings)

[ 0.00475905 -0.01075403  0.05508    ...  0.00051931 -0.00309993
  0.00704621]
[-0.03300949 -0.00130674  0.04349849 ... -0.01452754 -0.01621027
 -0.00568621]
[-0.02678444 -0.03558164  0.01822577 ... -0.01707526  0.00651021
  0.02531123]
[-0.02391892 -0.02314781  0.03573289 ... -0.01638242  0.00482307
  0.02800725]


In [30]:
embeddings_list = []
meta = []
for idx, chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    embeddings_list.append(vec.astype("float32"))
    meta.append({ "id": idx, "text": chunk })

In [31]:
meta

[{'id': 0,
  'text': "aking an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today"},
 {'id': 1,
  'text': ".5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 202"},
 {'id': 2,
  'text': 'ackgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron '},
 {'id': 3,
  'te

In [32]:
embeddings_list

[array([ 0.00475557, -0.01077392,  0.05507862, ...,  0.00050797,
        -0.00309985,  0.00702588], shape=(1536,), dtype=float32),
 array([-0.03300949, -0.00130674,  0.04349849, ..., -0.01452754,
        -0.01621027, -0.00568621], shape=(1536,), dtype=float32),
 array([-0.0266083 , -0.0364025 ,  0.01919609, ..., -0.01608548,
         0.0063193 ,  0.02537526], shape=(1536,), dtype=float32),
 array([-0.02391892, -0.02314781,  0.03573289, ..., -0.01638242,
         0.00482307,  0.02800725], shape=(1536,), dtype=float32)]

In [33]:
import numpy as np

xb = np.vstack(embeddings_list)
xb

array([[ 0.00475557, -0.01077392,  0.05507862, ...,  0.00050797,
        -0.00309985,  0.00702588],
       [-0.03300949, -0.00130674,  0.04349849, ..., -0.01452754,
        -0.01621027, -0.00568621],
       [-0.0266083 , -0.0364025 ,  0.01919609, ..., -0.01608548,
         0.0063193 ,  0.02537526],
       [-0.02391892, -0.02314781,  0.03573289, ..., -0.01638242,
         0.00482307,  0.02800725]], shape=(4, 1536), dtype=float32)

In [34]:
import faiss

index = faiss.IndexFlatIP(1536)
index.add(xb)

In [35]:
index_path = "index_data.faiss"
faiss.write_index(index, index_path)

In [36]:
import json

meta_path = "metadata.json"
with open(meta_path, "w") as f:
    for item in meta:
        f.write(json.dumps(item) + "\n")

In [37]:
query = "what is the mission of iNeuron"
q = generate_embeddings(query).astype("float32").reshape(1, -1)
faiss.normalize_L2(q)
index.search(q, 5)

(array([[ 5.7455552e-01,  5.5136782e-01,  5.2313298e-01,  5.0230521e-01,
         -3.4028235e+38]], dtype=float32),
 array([[ 2,  1,  3,  0, -1]]))